### ISSUE TITLE
Follow imports from packages 

### ISSUE THREAD

**Issue by arnonkehat** [wix/stylable-intelligence#147]
option 1:

```css
:import {
  -st-from: "../../node_modules/stylable-components/dist/src/components/date-picker/date-picker.st.css";
  -st-default: DatePicker;
}
```

option 2:
```css
:import {
  -st-from: "stylable-components/dist/src/components/date-picker/date-picker.st.css";
  -st-default: DatePicker;
}
```
both are legal and should work. 

however, the option 2 **works**, but shows an **error in intelligence.**
