### ISSUE TITLE
Pseudo-class validators do not receive hinting

### ISSUE THREAD

**Issue by tomrav** [wix/stylable-intelligence#195]
Currently, hinting is only provided for state definitions and their type. 
Hinting for each validator used in a type needs to be added

Example for missing hint:
```css
.myClass {
    -st-states: someState( string ( contains( [caret here] ) ) );
}
```
> String validator: `function contains(match: string)`
