### ISSUE TITLE
Pseudo-class: support hinting and completions for multiple states in a single definition

### ISSUE THREAD

**Issue by tomrav** [wix/stylable-intelligence#196]
Should include support for multiple lines:

Failing example:
```css
.myClass {
    -st-states: state1(string(contains(user))),
                       state2(number(min(2)));
}
```
