### ISSUE TITLE
Renaming classes works on every 2nd occasion.

### ISSUE THREAD

**Issue by talh78** [wix/stylable-intelligence#222]
```css

.firstButton {
    -st-states: shahar;
    padding: value(myPadding);
    background-color: black;
    border: 1px solid blue;
    color: white;
    outline: none;
    cursor: pointer;
}

.firstButton:hover {
    background-color: grey;
}

.firstButton:shahar {
    color: orange;
}
```

When renaming `.firstButton`, `.firstButton:hover` doesn't change
