### ISSUE TITLE
Variable name that is prefixed with other variable name displays two color pickers in :import block

### ISSUE THREAD

**Issue by talh78** [wix/stylable-intelligence#224]
file1.st.css:
```css
:vars {
    mya: rgb(255, 0, 0);
    myaa: green;
}

.root {
    color: value(myaa);
}
```

file2.st.css:
```css
:import {
    -st-from: "./file1.st.css";
    -st-named: myaa;
}
```

We get two color pickers next to `myaa` inside the import. Hovering above `myaa` shows and accentuates `mya`. 
Other places where `myaa` is used are displayed fine.
