### ISSUE TITLE
Wrong warning placement for "no component capilization" warning

### ISSUE THREAD

**Issue by talh78** [wix/stylable-intelligence#238]
```css
:import {
    -st-from: "../../components/tabs/tabs.st.css";
    -st-default: tab;
}
```

Green squiggly appears below:
    "../../components/`tab`s/tabs.st.css";
Instead of below:
    -st-default: `tab`;
