### ISSUE TITLE
stylable-intelligence ruins grid template formatting

### ISSUE THREAD

**Issue by alisey** [wix/stylable-intelligence#753]
Start with the following code:

```css
.foo {
    grid-template:
        "icon  name name ."    16px
        ".     type .    ."    16px
        ".     desc desc desc" 20px
        / 16px 3fr  2fr  4fr;
}
```

In VSCode, press Cmd + P, Format Document, get the following sad result:
```css
.foo {
    grid-template:
        "icon  name name ."16px ".     type .    ."16px ".     desc desc desc"20px / 16px 3fr 2fr 4fr;
}
```

If Prettier would support Stylable, we could just change the default formatter, but unfortunately it doesn't.
